version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: upfirst-postgres-dev
    environment:
      POSTGRES_USER: upfirst
      POSTGRES_PASSWORD: upfirst_dev_password
      POSTGRES_DB: upfirst_dev
    ports:
      - "5432:5432"
    volumes:
      - postgres_dev_data:/var/lib/postgresql/data

volumes:
  postgres_dev_data:
