version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: upfirst-postgres
    environment:
      POSTGRES_USER: upfirst
      POSTGRES_PASSWORD: upfirst_dev_password
      POSTGRES_DB: upfirst
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U upfirst"]
      interval: 10s
      timeout: 5s
      retries: 5

  nest-api:
    build:
      context: .
      dockerfile: apps/nest-api/Dockerfile
    container_name: upfirst-nest-api
    environment:
      NODE_ENV: production
      DATABASE_URL: postgresql://upfirst:upfirst_dev_password@postgres:5432/upfirst
      PORT: 4000
    ports:
      - "4000:4000"
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./prisma:/app/prisma
    command: sh -c "npx prisma migrate deploy && node apps/nest-api/dist/main.js"

  vite-frontend:
    build:
      context: .
      dockerfile: client/Dockerfile
    container_name: upfirst-vite-frontend
    ports:
      - "5000:80"
    depends_on:
      - nest-api

  nextjs-frontend:
    build:
      context: .
      dockerfile: apps/nextjs/Dockerfile
    container_name: upfirst-nextjs-frontend
    environment:
      NODE_ENV: production
      NEXT_PUBLIC_GRAPHQL_URL: http://nest-api:4000/graphql
    ports:
      - "3000:3000"
    depends_on:
      - nest-api

volumes:
  postgres_data:
